%range of motion plot of endpoint coordinates
%based on the recruitment curves for each muscle

%set path to data
path = '/Users/mariajantz/Documents/Work/data/kinematics/processed/'; 
filedate = '170221_'; 
filenum = [37:48];

%set the "default" position for the toe
%mark the position of each marker by default in xyz space

%get path generated by each of the muscles
%plot just endpoint
fig1 = figure(1); 
fig2 = figure(2); 
h1 = []; 
h2 = [];
for f = filenum
    load([path filedate num2str(f, '%02d') '_rat.mat']); 
    figure(1); hold on; 
    plot(rat.hip_bottom(1, 1), rat.hip_bottom(1, 2), 'o', 'color', 'k'); 
    plot(rat.toe(1, 1), rat.toe(1, 2), 'o', 'color', 'k'); 
    plot(rat.hip_top(1, 1), rat.hip_top(1, 2), 'o', 'color', 'r'); 
    h1(end+1) = plot(rat.toe(1:233, 1), rat.toe(1:233, 2), 'linewidth', 1, 'DisplayName', num2str(f)); 
    figure(2); hold on;
    plot(rat.hip_bottom(1, 1), rat.hip_bottom(1, 3), 'o', 'color', 'k'); 
    plot(rat.toe(1, 1), rat.toe(1, 3), 'o', 'color', 'k'); 
    plot(rat.hip_top(1, 1), rat.hip_top(1, 3), 'o', 'color', 'r'); 
    h2(end+1) = plot(rat.toe(1:233, 1), rat.toe(1:233, 3), 'linewidth', 1, 'DisplayName', num2str(f)); 
end
figure(1); %legend(h1);
ax = gca; 
ax.FontSize = 20; 
xlabel('\Delta X')
ylabel('\Delta Y')
figure(2); %legend(h2);
ax = gca; 
ax.FontSize = 20; 
xlabel('\Delta X')
ylabel('\Delta Z')


%deal with more complicated plotting